import { Agent, Manager, WeeklyPerformance, MonthlyResult, RCA, ActionItem, Notification } from '../types';

export const INITIAL_MANAGERS: Manager[] = [
  {
    id: 'mgr-495',
    name: 'SABI Prospere',
    nom: 'SABI',
    prenom: 'Prospère',
    matricule: '495',
    password: 'TP495',
    premier_login: false,
    locked_password: true,
    isGlobalAdmin: true,
  },
  {
    id: 'mgr-218',
    name: 'YOMEKPE Komlan Agbenyigan',
    nom: 'YOMEKPE',
    prenom: 'Komlan Agbenyigan',
    matricule: '218',
    password: 'TP218',
    premier_login: false,
    locked_password: false,
  },
  {
    id: 'mgr-391',
    name: 'HOUENASSOU Sidemeho Akofa',
    nom: 'HOUENASSOU',
    prenom: 'Sidemeho Akofa',
    matricule: '391',
    password: 'TP391',
    premier_login: false,
    locked_password: false,
  },
  {
    id: 'mgr-881',
    name: 'KPONOOR ZAMAH Goudjo Yao Emile',
    nom: 'KPONOOR ZAMAH',
    prenom: 'Goudjo Yao Emile',
    matricule: '881',
    password: 'TP881',
    premier_login: false,
    locked_password: false,
  },
  {
    id: 'mgr-1010',
    name: 'BAHUN-WILSON Adjei Amos Annointed A.',
    nom: 'BAHUN-WILSON',
    prenom: 'Adjei Amos Annointed A.',
    matricule: '1010',
    password: 'TP1010',
    premier_login: false,
    locked_password: false,
  },
  {
    id: 'mgr-563',
    name: 'AMADOU Fatimatou',
    nom: 'AMADOU',
    prenom: 'Fatimatou',
    matricule: '563',
    password: 'TP563',
    premier_login: false,
    locked_password: false,
  },
];

export const INITIAL_AGENTS: Agent[] = [
  {
    id: 'agent-1163',
    matricule_rh: '1163',
    nom_complet: 'TATOUNOU Shalom',
    nom: 'TATOUNOU',
    prenom: 'Shalom',
    manager_name: 'SABI Prospere',
    date_mep: '15/01/2024',
    contrat: 'CDI',
    statut_contrat: 'CDI N2',
    anciennete: '+ 3 mois',
    log_activite: 'lom_tatounou',
    premier_login: false,
    statut: 'actif',
    email: 'tatounou.s@amazon-support.com',
    role: 'agent',
    xp: 440,
    niveau: 2,
    badges: ['perfect_week'],
  },
  {
    id: 'agent-2347',
    matricule_rh: '2347',
    nom_complet: 'AZANLEDJI Kokou Boniface',
    nom: 'AZANLEDJI',
    prenom: 'Kokou Boniface',
    manager_name: 'SABI Prospere',
    date_mep: '10/02/2024',
    contrat: 'CDD',
    statut_contrat: 'ANP',
    anciennete: '+ 3 mois',
    log_activite: 'lom_boniface',
    premier_login: true,
    statut: 'actif',
    email: 'boniface.a@amazon-support.com',
    role: 'agent',
    xp: 260,
    niveau: 1,
    badges: [],
  },
  {
    id: 'agent-2177',
    matricule_rh: '2177',
    nom_complet: 'GANKUI Marie-josé',
    nom: 'GANKUI',
    prenom: 'Marie-josé',
    manager_name: 'SABI Prospere',
    date_mep: '01/03/2024',
    contrat: 'CDD',
    statut_contrat: 'ANP',
    anciennete: '+ 3 mois',
    log_activite: 'lom_marijo',
    premier_login: true,
    statut: 'actif',
    role: 'agent',
    xp: 320,
    niveau: 2,
    badges: ['top_csat'],
  },
  {
    id: 'agent-2178',
    matricule_rh: '2178',
    nom_complet: 'KIDIKOUNE Emma',
    nom: 'KIDIKOUNE',
    prenom: 'Emma',
    manager_name: 'SABI Prospere',
    date_mep: '12/03/2024',
    contrat: 'CDD',
    statut_contrat: 'ANP',
    anciennete: '+ 3 mois',
    log_activite: 'lom_emma',
    premier_login: true,
    statut: 'actif',
    role: 'agent',
    xp: 380,
    niveau: 2,
    badges: ['perfect_week'],
  },
  {
    id: 'agent-799',
    matricule_rh: '799',
    nom_complet: 'HOUEDJAGBAGBA Komlan Mawuko Clément',
    nom: 'HOUEDJAGBAGBA',
    prenom: 'Komlan Mawuko Clément',
    manager_name: 'SABI Prospere',
    date_mep: '05/11/2023',
    contrat: 'CDI',
    statut_contrat: 'CDI N2',
    anciennete: '+ 3 mois',
    log_activite: 'lom_gbagba',
    premier_login: true,
    statut: 'actif',
    role: 'agent',
    xp: 290,
    niveau: 1,
    badges: [],
  },
  {
    id: 'agent-2168',
    matricule_rh: '2168',
    nom_complet: 'LAWSON Sibi Lolita',
    nom: 'LAWSON',
    prenom: 'Sibi Lolita',
    manager_name: 'SABI Prospere',
    date_mep: '20/03/2024',
    contrat: 'CDD',
    statut_contrat: 'ANP',
    anciennete: '+ 3 mois',
    log_activite: 'lom_sibita',
    premier_login: true,
    statut: 'actif',
    role: 'agent',
    xp: 220,
    niveau: 1,
    badges: [],
  },
  {
    id: 'agent-551',
    matricule_rh: '551',
    nom_complet: 'TATRA Aman Emefa',
    nom: 'TATRA',
    prenom: 'Aman Emefa',
    manager_name: 'SABI Prospere',
    date_mep: '10/10/2023',
    contrat: 'CDI',
    statut_contrat: 'CDI N2',
    anciennete: '+ 3 mois',
    log_activite: 'lom_amane',
    premier_login: true,
    statut: 'actif',
    role: 'agent',
    xp: 410,
    niveau: 2,
    badges: ['perfect_week', 'top_csat'],
  },
  {
    id: 'agent-1132',
    matricule_rh: '1132',
    nom_complet: 'NTSUYIBOE Joanita',
    nom: 'NTSUYIBOE',
    prenom: 'Joanita',
    manager_name: 'SABI Prospere',
    date_mep: '01/01/2024',
    contrat: 'CDI',
    statut_contrat: 'CDI N2',
    anciennete: '+ 3 mois',
    log_activite: 'lom_joanita',
    premier_login: true,
    statut: 'actif',
    role: 'agent',
    xp: 490,
    niveau: 2,
    badges: ['perfect_week', 'speed_demon'],
  },
  {
    id: 'agent-1779',
    matricule_rh: '1779',
    nom_complet: 'AHADJI Akouavi Essenam',
    nom: 'AHADJI',
    prenom: 'Akouavi Essenam',
    manager_name: 'SABI Prospere',
    date_mep: '14/02/2024',
    contrat: 'CDD',
    statut_contrat: 'CDD',
    anciennete: '+ 3 mois',
    log_activite: 'lom_esenam',
    premier_login: true,
    statut: 'actif',
    role: 'agent',
    xp: 340,
    niveau: 2,
    badges: ['top_csat'],
  },
  {
    id: 'agent-1752',
    matricule_rh: '1752',
    nom_complet: 'NYAVOR Koukou There',
    nom: 'NYAVOR',
    prenom: 'Koukou There',
    manager_name: 'SABI Prospere',
    date_mep: '01/02/2024',
    contrat: 'CDD',
    statut_contrat: 'CDD',
    anciennete: '+ 3 mois',
    log_activite: 'lom_there',
    premier_login: true,
    statut: 'actif',
    role: 'agent',
    xp: 390,
    niveau: 2,
    badges: ['perfect_week'],
  },
  {
    id: 'agent-1863',
    matricule_rh: '1863',
    nom_complet: 'YAKE Calice Bidema',
    nom: 'YAKE',
    prenom: 'Calice Bidema',
    manager_name: 'SABI Prospere',
    date_mep: '05/02/2024',
    contrat: 'CDD',
    statut_contrat: 'CDD',
    anciennete: '+ 3 mois',
    log_activite: 'lom_calice',
    premier_login: true,
    statut: 'actif',
    role: 'agent',
    xp: 210,
    niveau: 1,
    badges: [],
  },
  {
    id: 'agent-1892',
    matricule_rh: '1892',
    nom_complet: 'OLOUDE Tony-Mike',
    nom: 'OLOUDE',
    prenom: 'Tony-Mike',
    manager_name: 'SABI Prospere',
    date_mep: '18/02/2024',
    contrat: 'CDD',
    statut_contrat: 'CDD',
    anciennete: '+ 3 mois',
    log_activite: 'lom_mike',
    premier_login: true,
    statut: 'actif',
    role: 'agent',
    xp: 280,
    niveau: 1,
    badges: [],
  },
  {
    id: 'agent-1905',
    matricule_rh: '1905',
    nom_complet: 'MIHAMI Koffi Philippe',
    nom: 'MIHAMI',
    prenom: 'Koffi Philippe',
    manager_name: 'SABI Prospere',
    date_mep: '20/02/2024',
    contrat: 'CDD',
    statut_contrat: 'CDD',
    anciennete: '+ 3 mois',
    log_activite: 'lom_philippe',
    premier_login: true,
    statut: 'actif',
    role: 'agent',
    xp: 310,
    niveau: 2,
    badges: [],
  },
  {
    id: 'agent-517',
    matricule_rh: '517',
    nom_complet: 'DOSSEH Yawa Sandrine',
    nom: 'DOSSEH',
    prenom: 'Yawa Sandrine',
    manager_name: 'SABI Prospere',
    date_mep: '01/09/2023',
    contrat: 'CDI',
    statut_contrat: 'CDI N2',
    anciennete: '+ 3 mois',
    log_activite: 'lom_yawad',
    premier_login: true,
    statut: 'actif',
    role: 'agent',
    xp: 300,
    niveau: 2,
    badges: [],
  },
  {
    id: 'agent-1032',
    matricule_rh: '1032',
    nom_complet: 'GBOGBO Aba Yawa Abigaïl Gloria',
    nom: 'GBOGBO',
    prenom: 'Aba Yawa Abigaïl Gloria',
    manager_name: 'SABI Prospere',
    date_mep: '15/12/2023',
    contrat: 'CDI',
    statut_contrat: 'CDI N2',
    anciennete: '+ 3 mois',
    log_activite: 'lom_gbogbo',
    premier_login: true,
    statut: 'actif',
    role: 'agent',
    xp: 240,
    niveau: 1,
    badges: [],
  },
  {
    id: 'agent-3000',
    matricule_rh: '3000',
    nom_complet: 'MOI Test',
    nom: 'MOI',
    prenom: 'Test',
    manager_name: 'SABI Prospere',
    date_mep: '01/06/2024',
    contrat: 'STG',
    statut_contrat: 'STG',
    anciennete: '- 3 mois',
    log_activite: 'lom_moi',
    premier_login: true,
    statut: 'actif',
    role: 'agent',
    xp: 150,
    niveau: 1,
    badges: [],
  },
  {
    id: 'agent-2210',
    matricule_rh: '2210',
    nom_complet: 'ADIKPETO Marc-Aurel',
    nom: 'ADIKPETO',
    prenom: 'Marc-Aurel',
    manager_name: 'SABI Prospere',
    date_mep: '15/02/2024',
    contrat: 'CDD',
    statut_contrat: 'CDD',
    anciennete: '+ 3 mois',
    log_activite: 'lom_aurel',
    premier_login: true,
    statut: 'actif',
    role: 'agent',
    xp: 270,
    niveau: 1,
    badges: [],
  },
  {
    id: 'agent-2211',
    matricule_rh: '2211',
    nom_complet: 'KOUASSI Afi Brigitte',
    nom: 'KOUASSI',
    prenom: 'Afi Brigitte',
    manager_name: 'SABI Prospere',
    date_mep: '01/03/2024',
    contrat: 'CDD',
    statut_contrat: 'CDD',
    anciennete: '+ 3 mois',
    log_activite: 'lom_brigitte',
    premier_login: true,
    statut: 'actif',
    role: 'agent',
    xp: 330,
    niveau: 2,
    badges: ['top_csat'],
  },
  {
    id: 'agent-2212',
    matricule_rh: '2212',
    nom_complet: 'DOGBE Mensah Serge',
    nom: 'DOGBE',
    prenom: 'Mensah Serge',
    manager_name: 'SABI Prospere',
    date_mep: '10/11/2023',
    contrat: 'CDI',
    statut_contrat: 'CDI N2',
    anciennete: '+ 3 mois',
    log_activite: 'lom_serge',
    premier_login: true,
    statut: 'actif',
    role: 'agent',
    xp: 410,
    niveau: 2,
    badges: ['perfect_week'],
  },
  {
    id: 'agent-2213',
    matricule_rh: '2213',
    nom_complet: 'ATSU Akossiwa Estelle',
    nom: 'ATSU',
    prenom: 'Akossiwa Estelle',
    manager_name: 'SABI Prospere',
    date_mep: '20/01/2024',
    contrat: 'CDD',
    statut_contrat: 'CDD',
    anciennete: '+ 3 mois',
    log_activite: 'lom_estelle',
    premier_login: true,
    statut: 'actif',
    role: 'agent',
    xp: 290,
    niveau: 1,
    badges: [],
  },
];

export const INITIAL_WEEKLY_PERFORMANCES: WeeklyPerformance[] = [
  // S31 - TATOUNOU Shalom
  {
    id: 'perf-1163-s31-phone',
    agent_id: 'agent-1163',
    agent_name: 'TATOUNOU Shalom',
    log_activite: 'lom_tatounou',
    manager_name: 'SABI Prospere',
    canal: 'Phone',
    semaine: 31,
    annee: 2026,
    yes: 185,
    no: 35,
    rap: 0.839,
    ccx: 0.906,
    tr: 0.141,
    dmt: 562,
    vol: 360,
    h_planifiees: 40,
    h_absence: 0,
    statut: 'En progression',
    feedback: 'Bonne gestion du volume Phone. L’écoute active et la réduction de la durée de traitement permettent de maintenir le DMT dans l’objectif.',
    axes_amelioration: 'Maintenir le focus sur la résolution au premier contact (RAP) pour dépasser 85%.',
    commentaires: 'Progression continue sur la fluidité des appels.',
    coaching: 'Concentrer les efforts sur la qualification directe du besoin client.',
    plan_action: 'Revoir le script de clarification initiale pendant 5 min chaque début de shift.',
  },
  {
    id: 'perf-1163-s31-email',
    agent_id: 'agent-1163',
    agent_name: 'TATOUNOU Shalom',
    log_activite: 'lom_tatounou',
    manager_name: 'SABI Prospere',
    canal: 'Email',
    semaine: 31,
    annee: 2026,
    yes: 140,
    no: 25,
    rap: 0.841,
    ccx: 0.937,
    tr: 0.188,
    dmt: 641,
    vol: 190,
    h_planifiees: 20,
    h_absence: 0,
    statut: 'Objectif atteint',
    feedback: 'Excellente rédaction des réponses email, CCX très satisfaisant.',
  },
  {
    id: 'perf-1163-s31-mu',
    agent_id: 'agent-1163',
    agent_name: 'TATOUNOU Shalom',
    log_activite: 'lom_tatounou',
    manager_name: 'SABI Prospere',
    canal: 'MU',
    semaine: 31,
    annee: 2026,
    yes: 120,
    no: 22,
    rap: 0.829,
    ccx: 0.933,
    tr: 0.191,
    dmt: 716,
    vol: 140,
    h_planifiees: 15,
    h_absence: 0,
    statut: 'À renforcer',
  },

  // S30 - TATOUNOU Shalom
  {
    id: 'perf-1163-s30-phone',
    agent_id: 'agent-1163',
    agent_name: 'TATOUNOU Shalom',
    log_activite: 'lom_tatounou',
    manager_name: 'SABI Prospere',
    canal: 'Phone',
    semaine: 30,
    annee: 2026,
    yes: 160,
    no: 40,
    rap: 0.679,
    ccx: 0.875,
    tr: 0.254,
    dmt: 0,
    vol: 220,
    h_planifiees: 35,
    h_absence: 2,
    statut: 'À renforcer',
    feedback: 'Taux de transfert anormalement élevé cette semaine. Réviser la grille d’escalade.',
  },
  {
    id: 'perf-1163-s30-email',
    agent_id: 'agent-1163',
    agent_name: 'TATOUNOU Shalom',
    log_activite: 'lom_tatounou',
    manager_name: 'SABI Prospere',
    canal: 'Email',
    semaine: 30,
    annee: 2026,
    yes: 150,
    no: 26,
    rap: 0.850,
    ccx: 0.958,
    tr: 0.205,
    dmt: 642,
    vol: 180,
  },
  {
    id: 'perf-1163-s30-mu',
    agent_id: 'agent-1163',
    agent_name: 'TATOUNOU Shalom',
    log_activite: 'lom_tatounou',
    manager_name: 'SABI Prospere',
    canal: 'MU',
    semaine: 30,
    annee: 2026,
    yes: 130,
    no: 22,
    rap: 0.854,
    ccx: 0.925,
    tr: 0.265,
    dmt: 0,
    vol: 150,
  },

  // S29 - TATOUNOU Shalom
  {
    id: 'perf-1163-s29-phone',
    agent_id: 'agent-1163',
    agent_name: 'TATOUNOU Shalom',
    log_activite: 'lom_tatounou',
    manager_name: 'SABI Prospere',
    canal: 'Phone',
    semaine: 29,
    annee: 2026,
    rap: 0.831,
    tr: 0.150,
    ccx: 0.920,
    dmt: 668,
    vol: 310,
  },
  {
    id: 'perf-1163-s29-email',
    agent_id: 'agent-1163',
    agent_name: 'TATOUNOU Shalom',
    log_activite: 'lom_tatounou',
    manager_name: 'SABI Prospere',
    canal: 'Email',
    semaine: 29,
    annee: 2026,
    rap: 0.829,
    tr: 0.187,
    ccx: 0.934,
    dmt: 651,
    vol: 175,
  },
  {
    id: 'perf-1163-s29-mu',
    agent_id: 'agent-1163',
    agent_name: 'TATOUNOU Shalom',
    log_activite: 'lom_tatounou',
    manager_name: 'SABI Prospere',
    canal: 'MU',
    semaine: 29,
    annee: 2026,
    rap: 0.850,
    tr: 0.226,
    ccx: 0.934,
    dmt: 705,
    vol: 160,
  },

  // S28 - TATOUNOU Shalom
  {
    id: 'perf-1163-s28-phone',
    agent_id: 'agent-1163',
    agent_name: 'TATOUNOU Shalom',
    log_activite: 'lom_tatounou',
    manager_name: 'SABI Prospere',
    canal: 'Phone',
    semaine: 28,
    annee: 2026,
    rap: 0.820,
    tr: 0.129,
    ccx: 0.906,
    dmt: 551,
    vol: 290,
  },
  {
    id: 'perf-1163-s28-email',
    agent_id: 'agent-1163',
    agent_name: 'TATOUNOU Shalom',
    log_activite: 'lom_tatounou',
    manager_name: 'SABI Prospere',
    canal: 'Email',
    semaine: 28,
    annee: 2026,
    rap: 0.863,
    tr: 0.188,
    ccx: 0.948,
    dmt: 680,
    vol: 180,
  },

  // S27 - TATOUNOU Shalom
  {
    id: 'perf-1163-s27-phone',
    agent_id: 'agent-1163',
    agent_name: 'TATOUNOU Shalom',
    log_activite: 'lom_tatounou',
    manager_name: 'SABI Prospere',
    canal: 'Phone',
    semaine: 27,
    annee: 2026,
    rap: 0.828,
    tr: 0.163,
    ccx: 0.906,
    dmt: 621,
    vol: 280,
  },

  // S31 - AZANLEDJI Kokou Boniface
  {
    id: 'perf-2347-s31-phone',
    agent_id: 'agent-2347',
    agent_name: 'AZANLEDJI Kokou Boniface',
    log_activite: 'lom_boniface',
    manager_name: 'SABI Prospere',
    canal: 'Phone',
    semaine: 31,
    annee: 2026,
    rap: 0.810,
    tr: 0.142,
    ccx: 0.902,
    dmt: 570,
    vol: 360,
  },
  {
    id: 'perf-2347-s31-email',
    agent_id: 'agent-2347',
    agent_name: 'AZANLEDJI Kokou Boniface',
    log_activite: 'lom_boniface',
    manager_name: 'SABI Prospere',
    canal: 'Email',
    semaine: 31,
    annee: 2026,
    rap: 0.842,
    tr: 0.183,
    ccx: 0.938,
    dmt: 729,
    vol: 54,
  },
  {
    id: 'perf-2347-s31-mu',
    agent_id: 'agent-2347',
    agent_name: 'AZANLEDJI Kokou Boniface',
    log_activite: 'lom_boniface',
    manager_name: 'SABI Prospere',
    canal: 'MU',
    semaine: 31,
    annee: 2026,
    rap: 0.823,
    tr: 0.193,
    ccx: 0.960,
    dmt: 729,
    vol: 67,
  },

  // S31 - GANKUI Marie-josé
  {
    id: 'perf-2177-s31-phone',
    agent_id: 'agent-2177',
    agent_name: 'GANKUI Marie-josé',
    log_activite: 'lom_marijo',
    manager_name: 'SABI Prospere',
    canal: 'Phone',
    semaine: 31,
    annee: 2026,
    rap: 0.826,
    tr: 0.145,
    ccx: 0.901,
    dmt: 650,
    vol: 221,
  },
  {
    id: 'perf-2177-s31-email',
    agent_id: 'agent-2177',
    agent_name: 'GANKUI Marie-josé',
    log_activite: 'lom_marijo',
    manager_name: 'SABI Prospere',
    canal: 'Email',
    semaine: 31,
    annee: 2026,
    rap: 0.845,
    tr: 0.182,
    ccx: 0.954,
    dmt: 665,
    vol: 79,
  },
  {
    id: 'perf-2177-s31-mu',
    agent_id: 'agent-2177',
    agent_name: 'GANKUI Marie-josé',
    log_activite: 'lom_marijo',
    manager_name: 'SABI Prospere',
    canal: 'MU',
    semaine: 31,
    annee: 2026,
    rap: 0.822,
    tr: 0.220,
    ccx: 0.941,
    dmt: 716,
    vol: 71,
  },

  // S31 - KIDIKOUNE Emma
  {
    id: 'perf-2178-s31-phone',
    agent_id: 'agent-2178',
    agent_name: 'KIDIKOUNE Emma',
    log_activite: 'lom_emma',
    manager_name: 'SABI Prospere',
    canal: 'Phone',
    semaine: 31,
    annee: 2026,
    rap: 0.826,
    tr: 0.174,
    ccx: 0.934,
    dmt: 564,
    vol: 309,
  },
  {
    id: 'perf-2178-s31-email',
    agent_id: 'agent-2178',
    agent_name: 'KIDIKOUNE Emma',
    log_activite: 'lom_emma',
    manager_name: 'SABI Prospere',
    canal: 'Email',
    semaine: 31,
    annee: 2026,
    rap: 0.874,
    tr: 0.223,
    ccx: 0.937,
    dmt: 682,
    vol: 79,
  },
  {
    id: 'perf-2178-s31-mu',
    agent_id: 'agent-2178',
    agent_name: 'KIDIKOUNE Emma',
    log_activite: 'lom_emma',
    manager_name: 'SABI Prospere',
    canal: 'MU',
    semaine: 31,
    annee: 2026,
    rap: 0.871,
    tr: 0.192,
    ccx: 0.946,
    dmt: 690,
    vol: 119,
  },

  // S31 - HOUEDJAGBAGBA Komlan Mawuko Clément
  {
    id: 'perf-799-s31-phone',
    agent_id: 'agent-799',
    agent_name: 'HOUEDJAGBAGBA Komlan Mawuko Clément',
    log_activite: 'lom_gbagba',
    manager_name: 'SABI Prospere',
    canal: 'Phone',
    semaine: 31,
    annee: 2026,
    rap: 0.855,
    tr: 0.120,
    ccx: 0.929,
    dmt: 607,
    vol: 300,
  },
  {
    id: 'perf-799-s31-email',
    agent_id: 'agent-799',
    agent_name: 'HOUEDJAGBAGBA Komlan Mawuko Clément',
    log_activite: 'lom_gbagba',
    manager_name: 'SABI Prospere',
    canal: 'Email',
    semaine: 31,
    annee: 2026,
    rap: 0.820,
    tr: 0.216,
    ccx: 0.946,
    dmt: 677,
    vol: 121,
  },
  {
    id: 'perf-799-s31-mu',
    agent_id: 'agent-799',
    agent_name: 'HOUEDJAGBAGBA Komlan Mawuko Clément',
    log_activite: 'lom_gbagba',
    manager_name: 'SABI Prospere',
    canal: 'MU',
    semaine: 31,
    annee: 2026,
    rap: 0.864,
    tr: 0.206,
    ccx: 0.944,
    dmt: 654,
    vol: 30,
  },

  // S31 - LAWSON Sibi Lolita
  {
    id: 'perf-2168-s31-phone',
    agent_id: 'agent-2168',
    agent_name: 'LAWSON Sibi Lolita',
    log_activite: 'lom_sibita',
    manager_name: 'SABI Prospere',
    canal: 'Phone',
    semaine: 31,
    annee: 2026,
    rap: 0.813,
    tr: 0.137,
    ccx: 0.920,
    dmt: 588,
    vol: 283,
  },

  // S31 - TATRA Aman Emefa
  {
    id: 'perf-551-s31-phone',
    agent_id: 'agent-551',
    agent_name: 'TATRA Aman Emefa',
    log_activite: 'lom_amane',
    manager_name: 'SABI Prospere',
    canal: 'Phone',
    semaine: 31,
    annee: 2026,
    rap: 0.835,
    tr: 0.143,
    ccx: 0.935,
    dmt: 638,
    vol: 317,
  },

  // S31 - NTSUYIBOE Joanita
  {
    id: 'perf-1132-s31-phone',
    agent_id: 'agent-1132',
    agent_name: 'NTSUYIBOE Joanita',
    log_activite: 'lom_joanita',
    manager_name: 'SABI Prospere',
    canal: 'Phone',
    semaine: 31,
    annee: 2026,
    rap: 0.859,
    tr: 0.125,
    ccx: 0.942,
    dmt: 545,
    vol: 380,
  },

  // S31 - OLOUDE Tony-Mike
  {
    id: 'perf-1892-s31-phone',
    agent_id: 'agent-1892',
    agent_name: 'OLOUDE Tony-Mike',
    log_activite: 'lom_mike',
    manager_name: 'SABI Prospere',
    canal: 'Phone',
    semaine: 31,
    annee: 2026,
    rap: 0.859,
    tr: 0.166,
    ccx: 0.907,
    dmt: 652,
    vol: 225,
  },

  // S31 - MIHAMI Koffi Philippe
  {
    id: 'perf-1905-s31-phone',
    agent_id: 'agent-1905',
    agent_name: 'MIHAMI Koffi Philippe',
    log_activite: 'lom_philippe',
    manager_name: 'SABI Prospere',
    canal: 'Phone',
    semaine: 31,
    annee: 2026,
    rap: 0.852,
    tr: 0.120,
    ccx: 0.913,
    dmt: 582,
    vol: 168,
  },

  // S31 - YAKE Calice Bidema
  {
    id: 'perf-1863-s31-phone',
    agent_id: 'agent-1863',
    agent_name: 'YAKE Calice Bidema',
    log_activite: 'lom_calice',
    manager_name: 'SABI Prospere',
    canal: 'Phone',
    semaine: 31,
    annee: 2026,
    rap: 0.822,
    tr: 0.138,
    ccx: 0.925,
    dmt: 556,
    vol: 344,
  },

  // S31 - DOSSEH Yawa Sandrine
  {
    id: 'perf-517-s31-phone',
    agent_id: 'agent-517',
    agent_name: 'DOSSEH Yawa Sandrine',
    log_activite: 'lom_yawad',
    manager_name: 'SABI Prospere',
    canal: 'Phone',
    semaine: 31,
    annee: 2026,
    rap: 0.819,
    tr: 0.167,
    ccx: 0.911,
    dmt: 664,
    vol: 144,
  },
];

export const INITIAL_MONTHLY_RESULTS: MonthlyResult[] = [
  {
    id: 'mres-1163-202607',
    agent_id: 'agent-1163',
    matricule_rh: '1163',
    agent_name: 'TATOUINOU Shalom',
    manager_name: 'SABI Prospere',
    anciennete: '+ 3 mois',
    mois_label: 'Juillet 2026',
    mois_key: '2026-07',
    annee: 2026,
    numero_mois: 7,
    vol_total: 1970,
    poids_phone: 62.5,
    poids_email: 22.3,
    poids_mu: 15.2,
    contrib_phone: 12500,
    contrib_email: 5200,
    contrib_mu: 4400,
    pv_sans_presence: 22100,
    presence: 93.14,
    pv_finale: 20669,
    statut: 'En progression',
    commentaire: 'Bon comportement global. Travailler la maîtrise du DMT sur le canal MU.',
  },
  {
    id: 'mres-1132-202607',
    agent_id: 'agent-1132',
    matricule_rh: '1132',
    agent_name: 'NTSUYIBOE Joanita',
    manager_name: 'SABI Prospere',
    anciennete: '+ 3 mois',
    mois_label: 'Juillet 2026',
    mois_key: '2026-07',
    annee: 2026,
    numero_mois: 7,
    vol_total: 1364,
    poids_phone: 75.0,
    poids_email: 15.0,
    poids_mu: 10.0,
    contrib_phone: 28500,
    contrib_email: 6200,
    contrib_mu: 4400,
    pv_sans_presence: 39100,
    presence: 91.75,
    pv_finale: 35910,
    statut: 'En progression',
  },
  {
    id: 'mres-551-202607',
    agent_id: 'agent-551',
    matricule_rh: '551',
    agent_name: 'TATRA Aman Emefa',
    manager_name: 'SABI Prospere',
    anciennete: '+ 3 mois',
    mois_label: 'Juillet 2026',
    mois_key: '2026-07',
    annee: 2026,
    numero_mois: 7,
    vol_total: 1206,
    poids_phone: 80.0,
    poids_email: 12.0,
    poids_mu: 8.0,
    contrib_phone: 26000,
    contrib_email: 5200,
    contrib_mu: 3000,
    pv_sans_presence: 34200,
    presence: 89.18,
    pv_finale: 30516,
    statut: 'En progression',
  },
  {
    id: 'mres-1752-202607',
    agent_id: 'agent-1752',
    matricule_rh: '1752',
    agent_name: 'NYAVOR Koukou There',
    manager_name: 'SABI Prospere',
    anciennete: '+ 3 mois',
    mois_label: 'Juillet 2026',
    mois_key: '2026-07',
    annee: 2026,
    numero_mois: 7,
    vol_total: 1850,
    poids_phone: 70.0,
    poids_email: 20.0,
    poids_mu: 10.0,
    contrib_phone: 24000,
    contrib_email: 5800,
    contrib_mu: 4000,
    pv_sans_presence: 33800,
    presence: 90.08,
    pv_finale: 30448,
    statut: 'En progression',
  },
  {
    id: 'mres-2178-202607',
    agent_id: 'agent-2178',
    matricule_rh: '2178',
    agent_name: 'KIDIKOUNE Emma',
    manager_name: 'SABI Prospere',
    anciennete: '+ 3 mois',
    mois_label: 'Juillet 2026',
    mois_key: '2026-07',
    annee: 2026,
    numero_mois: 7,
    vol_total: 1927,
    poids_phone: 61.0,
    poids_email: 15.5,
    poids_mu: 23.5,
    contrib_phone: 18500,
    contrib_email: 6100,
    contrib_mu: 5750,
    pv_sans_presence: 30350,
    presence: 96.48,
    pv_finale: 29274,
    statut: 'En progression',
  },
  {
    id: 'mres-1779-202607',
    agent_id: 'agent-1779',
    matricule_rh: '1779',
    agent_name: 'AHADJI Akouavi Essenam',
    manager_name: 'SABI Prospere',
    anciennete: '+ 3 mois',
    mois_label: 'Juillet 2026',
    mois_key: '2026-07',
    annee: 2026,
    numero_mois: 7,
    vol_total: 1450,
    poids_phone: 68.0,
    poids_email: 20.0,
    poids_mu: 12.0,
    contrib_phone: 20000,
    contrib_email: 5500,
    contrib_mu: 4400,
    pv_sans_presence: 29900,
    presence: 96.17,
    pv_finale: 28754,
    statut: 'En progression',
  },
  {
    id: 'mres-2168-202607',
    agent_id: 'agent-2168',
    matricule_rh: '2168',
    agent_name: 'LAWSON Sibi Lolita',
    manager_name: 'SABI Prospere',
    anciennete: '+ 3 mois',
    mois_label: 'Juillet 2026',
    mois_key: '2026-07',
    annee: 2026,
    numero_mois: 7,
    vol_total: 2138,
    pv_sans_presence: 16000,
    presence: 94.22,
    pv_finale: 15071,
    statut: 'À renforcer',
  },
  {
    id: 'mres-2347-202607',
    agent_id: 'agent-2347',
    matricule_rh: '2347',
    agent_name: 'AZANLEDJI Kokou Boniface',
    manager_name: 'SABI Prospere',
    anciennete: '+ 3 mois',
    mois_label: 'Juillet 2026',
    mois_key: '2026-07',
    annee: 2026,
    numero_mois: 7,
    vol_total: 1922,
    pv_sans_presence: 26800,
    presence: 94.28,
    pv_finale: 25336,
    statut: 'En progression',
  },
  {
    id: 'mres-2177-202607',
    agent_id: 'agent-2177',
    matricule_rh: '2177',
    agent_name: 'PEKEMSI Edmond Eyana',
    manager_name: 'SABI Prospere',
    anciennete: '+ 3 mois',
    mois_label: 'Juillet 2026',
    mois_key: '2026-07',
    annee: 2026,
    numero_mois: 7,
    vol_total: 1495,
    pv_sans_presence: 29250,
    presence: 88.99,
    pv_finale: 26035,
    statut: 'En progression',
  },
  {
    id: 'mres-1032-202607',
    agent_id: 'agent-1032',
    matricule_rh: '1032',
    agent_name: 'GBOGBO Aba Yawa Abigaïl Gloria',
    manager_name: 'SABI Prospere',
    anciennete: '+ 3 mois',
    mois_label: 'Juillet 2026',
    mois_key: '2026-07',
    annee: 2026,
    numero_mois: 7,
    vol_total: 1897,
    pv_sans_presence: 16250,
    presence: 93.26,
    pv_finale: 15163,
    statut: 'À renforcer',
  },
];

export const INITIAL_RCAS: RCA[] = [
  {
    id: 'rca-1',
    agent_id: 'agent-1163',
    agent_name: 'TATOUNOU Shalom',
    semaine: 30,
    annee: 2026,
    kpi_concerne: 'TR',
    description: 'Taux de transfert anormalement élevé (25.4% vs cible 14.5%) en S30 sur le canal Phone.',
    analyse_cause: 'Escalade prématurée vers le N2 lors des demandes de remboursement complexes sur produits reconditionnés sans vérifier la FAQ V2.',
    statut: 'en_cours',
    priorite: 'haute',
    created_by_name: 'SABI Prospere',
  },
  {
    id: 'rca-2',
    agent_id: 'agent-2347',
    agent_name: 'AZANLEDJI Kokou Boniface',
    semaine: 31,
    annee: 2026,
    kpi_concerne: 'DMT',
    description: 'DMT Email & MU supérieur à 720s en S31.',
    analyse_cause: 'Recherche manuelle d’informations de livraison au lieu de consulter directement le portail logistique interne.',
    statut: 'ouvert',
    priorite: 'moyenne',
    created_by_name: 'SABI Prospere',
  },
];

export const INITIAL_ACTION_ITEMS: ActionItem[] = [
  {
    id: 'act-1',
    rca_id: 'rca-1',
    agent_id: 'agent-1163',
    agent_name: 'TATOUNOU Shalom',
    action: 'Session de formation de 30 min sur l’arbre de décision de remboursement.',
    responsable: 'Formateur / Manager',
    echeance: '2026-08-15',
    statut: 'en_cours',
    progres: 50,
  },
  {
    id: 'act-2',
    rca_id: 'rca-1',
    agent_id: 'agent-1163',
    agent_name: 'TATOUNOU Shalom',
    action: 'Double écoute de 5 appels avec transfert par le manager.',
    responsable: 'SABI Prospere',
    echeance: '2026-08-18',
    statut: 'a_faire',
    progres: 0,
  },
  {
    id: 'act-3',
    rca_id: 'rca-2',
    agent_id: 'agent-2347',
    agent_name: 'AZANLEDJI Kokou Boniface',
    action: 'Mettre à jour les raccourcis navigateur vers le portail suivi colis.',
    responsable: 'AZANLEDJI Kokou Boniface',
    echeance: '2026-08-12',
    statut: 'a_faire',
    progres: 0,
  },
];

export const INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    agent_id: 'agent-1163',
    type: 'info',
    titre: 'Nouveau feedback - S31',
    message: 'SABI Prospere a publié votre feedback pour la semaine 31. Consultez-le dans votre espace.',
    lu: false,
    semaine: 31,
    kpi: 'feedback',
    created_date: '2026-08-05T10:00:00Z',
  },
  {
    id: 'notif-2',
    agent_id: 'agent-1163',
    type: 'success',
    titre: 'Objectif atteint en S31 !',
    message: 'Félicitations, vous avez atteint l’objectif sur le canal Email en S31.',
    lu: false,
    semaine: 31,
    kpi: 'rap',
    created_date: '2026-08-06T14:30:00Z',
  },
];
