import { Agent, Manager, WeeklyPerformance, MonthlyResult, RCA, ActionItem, Notification } from '../types';

export const INITIAL_MANAGERS: Manager[] = [
  {
    id: 'mgr-495',
    name: 'SABI Prospere',
    nom: 'SABI',
    prenom: 'Prospère',
    matricule: '495',
    premier_login: false,
    locked_password: true,
    isGlobalAdmin: true,
  },
  {
    id: 'mgr-218',
    name: 'YOMEKPE Komlan Agbenyigan',
    nom: 'YOMEKPE',
    prenom: 'Komlan Agbenyigan',
    matricule: '218',
    premier_login: false,
    locked_password: false,
  },
  {
    id: 'mgr-391',
    name: 'HOUENASSOU Sidemeho Akofa',
    nom: 'HOUENASSOU',
    prenom: 'Sidemeho Akofa',
    matricule: '391',
    premier_login: false,
    locked_password: false,
  },
  {
    id: 'mgr-881',
    name: 'KPONOOR ZAMAH Goudjo Yao Emile',
    nom: 'KPONOOR ZAMAH',
    prenom: 'Goudjo Yao Emile',
    matricule: '881',
    premier_login: false,
    locked_password: false,
  },
  {
    id: 'mgr-1010',
    name: 'BAHUN-WILSON Adjei Amos Annointed A.',
    nom: 'BAHUN-WILSON',
    prenom: 'Adjei Amos Annointed A.',
    matricule: '1010',
    premier_login: false,
    locked_password: false,
  },
  {
    id: 'mgr-563',
    name: 'AMADOU Fatimatou',
    nom: 'AMADOU',
    prenom: 'Fatimatou',
    matricule: '563',
    premier_login: false,
    locked_password: false,
  },
];

export const INITIAL_AGENTS: Agent[] = [
  {
    "id": "agent-17",
    "matricule_rh": "17",
    "nom_complet": "KLU Amepui Elom",
    "nom": "KLU",
    "prenom": "Amepui Elom",
    "manager_name": "YOMEKPE Komlan Agbenyigan",
    "date_mep": "24/09/2018",
    "contrat": "CDI",
    "statut_contrat": "CDI N2",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_elom",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_elom@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-65",
    "matricule_rh": "65",
    "nom_complet": "HOUNDJAGO Luvossi Mago Nini",
    "nom": "HOUNDJAGO",
    "prenom": "Luvossi Mago Nini",
    "manager_name": "BAHUN-WILSON Adjei Amos Annointed A.",
    "date_mep": "16/10/2018",
    "contrat": "CDI",
    "statut_contrat": "CDI N2",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_mago",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_mago@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-278",
    "matricule_rh": "278",
    "nom_complet": "FREITAS JUNIOR KOSSI HORATIO",
    "nom": "FREITAS",
    "prenom": "JUNIOR KOSSI HORATIO",
    "manager_name": "KPONOOR ZAMAH Goudjo Yao Emile",
    "date_mep": "22/07/2019",
    "contrat": "CDI",
    "statut_contrat": "CDI N2",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_horatio",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_horatio@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-322",
    "matricule_rh": "322",
    "nom_complet": "HIHETAH Kokui Délali",
    "nom": "HIHETAH",
    "prenom": "Kokui Délali",
    "manager_name": "HOUENASSOU Sidemeho Akofa",
    "date_mep": "02/09/2019",
    "contrat": "CDI",
    "statut_contrat": "CDI N2",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_kokui",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_kokui@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-421",
    "matricule_rh": "421",
    "nom_complet": "SENAYA Adjo Genette",
    "nom": "SENAYA",
    "prenom": "Adjo Genette",
    "manager_name": "YOMEKPE Komlan Agbenyigan",
    "date_mep": "12/11/2019",
    "contrat": "CDI",
    "statut_contrat": "CDI N2",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_senaya",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_senaya@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-517",
    "matricule_rh": "517",
    "nom_complet": "DOSSEH Yawa Sandrine",
    "nom": "DOSSEH",
    "prenom": "Yawa Sandrine",
    "manager_name": "SABI Prospere",
    "date_mep": "13/07/2020",
    "contrat": "CDI",
    "statut_contrat": "CDI N2",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_yawad",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_yawad@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-551",
    "matricule_rh": "551",
    "nom_complet": "TATRA Aman Emefa",
    "nom": "TATRA",
    "prenom": "Aman Emefa",
    "manager_name": "SABI Prospere",
    "date_mep": "14/07/2020",
    "contrat": "CDI",
    "statut_contrat": "CDI N2",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_amane",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_amane@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-552",
    "matricule_rh": "552",
    "nom_complet": "TSATSI Yao Léon",
    "nom": "TSATSI",
    "prenom": "Yao Léon",
    "manager_name": "KPONOOR ZAMAH Goudjo Yao Emile",
    "date_mep": "14/07/2020",
    "contrat": "CDI",
    "statut_contrat": "CDI N2",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_leont",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_leont@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-636",
    "matricule_rh": "636",
    "nom_complet": "AWADE Tetouwalla",
    "nom": "AWADE",
    "prenom": "Tetouwalla",
    "manager_name": "HOUENASSOU Sidemeho Akofa",
    "date_mep": "31/08/2020",
    "contrat": "CDI",
    "statut_contrat": "CDI N2",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_wallaa",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_wallaa@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-694",
    "matricule_rh": "694",
    "nom_complet": "SEDOU Adjo Bilola Vicentia",
    "nom": "SEDOU",
    "prenom": "Adjo Bilola Vicentia",
    "manager_name": "KPONOOR ZAMAH Goudjo Yao Emile",
    "date_mep": "25/10/2021",
    "contrat": "CDI",
    "statut_contrat": "CDI N2",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_sedou",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_sedou@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-768",
    "matricule_rh": "768",
    "nom_complet": "LIGBESSIM Bidalinam",
    "nom": "LIGBESSIM",
    "prenom": "Bidalinam",
    "manager_name": "HOUENASSOU Sidemeho Akofa",
    "date_mep": "04/04/2022",
    "contrat": "CDI",
    "statut_contrat": "CDI N2",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_bidalinam",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_bidalinam@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-772",
    "matricule_rh": "772",
    "nom_complet": "SAPARAPA Nihadat",
    "nom": "SAPARAPA",
    "prenom": "Nihadat",
    "manager_name": "HOUENASSOU Sidemeho Akofa",
    "date_mep": "04/04/2022",
    "contrat": "CDI",
    "statut_contrat": "CDI N2",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_nihadat",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_nihadat@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-789",
    "matricule_rh": "789",
    "nom_complet": "DAMESSI Akou Elawoe",
    "nom": "DAMESSI",
    "prenom": "Akou Elawoe",
    "manager_name": "KPONOOR ZAMAH Goudjo Yao Emile",
    "date_mep": "25/10/2021",
    "contrat": "CDI",
    "statut_contrat": "CDI N2",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_elawoe",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_elawoe@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-792",
    "matricule_rh": "792",
    "nom_complet": "DZIKPO Adjo Brigitte",
    "nom": "DZIKPO",
    "prenom": "Adjo Brigitte",
    "manager_name": "YOMEKPE Komlan Agbenyigan",
    "date_mep": "25/10/2021",
    "contrat": "CDI",
    "statut_contrat": "CDI N2",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_brigitte",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_brigitte@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-798",
    "matricule_rh": "798",
    "nom_complet": "GUELEWOUYE Logossi Sidoine",
    "nom": "GUELEWOUYE",
    "prenom": "Logossi Sidoine",
    "manager_name": "KPONOOR ZAMAH Goudjo Yao Emile",
    "date_mep": "25/10/2021",
    "contrat": "CDI",
    "statut_contrat": "CDI N2",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_sidoine",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_sidoine@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-870",
    "matricule_rh": "870",
    "nom_complet": "ADENYO Adjo Odile",
    "nom": "ADENYO",
    "prenom": "Adjo Odile",
    "manager_name": "HOUENASSOU Sidemeho Akofa",
    "date_mep": "01/06/2022",
    "contrat": "CDI",
    "statut_contrat": "CDI N2",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_adenadj",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_adenadj@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-877",
    "matricule_rh": "877",
    "nom_complet": "DJOSSE Ahovi Gretta",
    "nom": "DJOSSE",
    "prenom": "Ahovi Gretta",
    "manager_name": "KPONOOR ZAMAH Goudjo Yao Emile",
    "date_mep": "01/06/2022",
    "contrat": "CDI",
    "statut_contrat": "CDI N2",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_djosaho",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_djosaho@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-878",
    "matricule_rh": "878",
    "nom_complet": "DZESSOU Akoko Francine",
    "nom": "DZESSOU",
    "prenom": "Akoko Francine",
    "manager_name": "YOMEKPE Komlan Agbenyigan",
    "date_mep": "01/06/2022",
    "contrat": "CDI",
    "statut_contrat": "CDI N2",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_dzesako",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_dzesako@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-879",
    "matricule_rh": "879",
    "nom_complet": "KINGSLEY Elizabeth",
    "nom": "KINGSLEY",
    "prenom": "Elizabeth",
    "manager_name": "YOMEKPE Komlan Agbenyigan",
    "date_mep": "01/06/2022",
    "contrat": "CDI",
    "statut_contrat": "CDI N2",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_eliza",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_eliza@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-898",
    "matricule_rh": "898",
    "nom_complet": "KIFALANG Komivi essolakna",
    "nom": "KIFALANG",
    "prenom": "Komivi essolakna",
    "manager_name": "KPONOOR ZAMAH Goudjo Yao Emile",
    "date_mep": "06/06/2022",
    "contrat": "CDI",
    "statut_contrat": "CDI N2",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_kifesso",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_kifesso@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-960",
    "matricule_rh": "960",
    "nom_complet": "FOLLY Folly Gérarld",
    "nom": "FOLLY",
    "prenom": "Folly Gérarld",
    "manager_name": "HOUENASSOU Sidemeho Akofa",
    "date_mep": "22/05/2023",
    "contrat": "CDI",
    "statut_contrat": "CDI N2",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_foly",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_foly@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-969",
    "matricule_rh": "969",
    "nom_complet": "ZOSSOU KoKou Elom",
    "nom": "ZOSSOU",
    "prenom": "KoKou Elom",
    "manager_name": "YOMEKPE Komlan Agbenyigan",
    "date_mep": "12/09/2022",
    "contrat": "CDI",
    "statut_contrat": "CDI N2",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_kozo",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_kozo@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-1007",
    "matricule_rh": "1007",
    "nom_complet": "AFANOU Inés Tiffany Ablavi",
    "nom": "AFANOU",
    "prenom": "Inés Tiffany Ablavi",
    "manager_name": "YOMEKPE Komlan Agbenyigan",
    "date_mep": "22/05/2023",
    "contrat": "CDI",
    "statut_contrat": "CDI N2",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_ablanou",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_ablanou@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-1032",
    "matricule_rh": "1032",
    "nom_complet": "GBOGBO Aba Yawa Abigaïl Gloria",
    "nom": "GBOGBO",
    "prenom": "Aba Yawa Abigaïl Gloria",
    "manager_name": "SABI Prospere",
    "date_mep": "22/05/2023",
    "contrat": "CDI",
    "statut_contrat": "CDI N2",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_gboya",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_gboya@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-1036",
    "matricule_rh": "1036",
    "nom_complet": "PEKEMSI Edmond Eyana",
    "nom": "PEKEMSI",
    "prenom": "Edmond Eyana",
    "manager_name": "SABI Prospere",
    "date_mep": "22/05/2023",
    "contrat": "CDI",
    "statut_contrat": "CDI N2",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_kemsi",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_kemsi@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-1132",
    "matricule_rh": "1132",
    "nom_complet": "NTSUYIBOE Joanita",
    "nom": "NTSUYIBOE",
    "prenom": "Joanita",
    "manager_name": "SABI Prospere",
    "date_mep": "21/08/2023",
    "contrat": "CDI",
    "statut_contrat": "CDI N1",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_boe",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_boe@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-1158",
    "matricule_rh": "1158",
    "nom_complet": "GAVITSE Michel",
    "nom": "GAVITSE",
    "prenom": "Michel",
    "manager_name": "KPONOOR ZAMAH Goudjo Yao Emile",
    "date_mep": "11/09/2023",
    "contrat": "CDI",
    "statut_contrat": "CDI N2",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_miche",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_miche@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-1163",
    "matricule_rh": "1163",
    "nom_complet": "TATOUNOU Shalom",
    "nom": "TATOUNOU",
    "prenom": "Shalom",
    "manager_name": "SABI Prospere",
    "date_mep": "11/09/2023",
    "contrat": "CDI",
    "statut_contrat": "CDI N1",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_tatou",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_tatou@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-1647",
    "matricule_rh": "1647",
    "nom_complet": "BELEYI Pizem Aline",
    "nom": "BELEYI",
    "prenom": "Pizem Aline",
    "manager_name": "YOMEKPE Komlan Agbenyigan",
    "date_mep": "09/09/2024",
    "contrat": "CDI",
    "statut_contrat": "CDI N1",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_pizem",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_pizem@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-1659",
    "matricule_rh": "1659",
    "nom_complet": "EKLOU Abla Romaine",
    "nom": "EKLOU",
    "prenom": "Abla Romaine",
    "manager_name": "YOMEKPE Komlan Agbenyigan",
    "date_mep": "09/09/2024",
    "contrat": "CDI",
    "statut_contrat": "CDI N1",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_romaine",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_romaine@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-1691",
    "matricule_rh": "1691",
    "nom_complet": "HATTA Dessa'ana Maxime",
    "nom": "HATTA",
    "prenom": "Dessa'ana Maxime",
    "manager_name": "YOMEKPE Komlan Agbenyigan",
    "date_mep": "09/09/2024",
    "contrat": "CDD",
    "statut_contrat": "CDD",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_dessana",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_dessana@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-1714",
    "matricule_rh": "1714",
    "nom_complet": "Amavi Kodjo Rémi",
    "nom": "Amavi",
    "prenom": "Kodjo Rémi",
    "manager_name": "YOMEKPE Komlan Agbenyigan",
    "date_mep": "23/09/2024",
    "contrat": "CDD",
    "statut_contrat": "CDD",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_remi",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_remi@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-1741",
    "matricule_rh": "1741",
    "nom_complet": "ADJOGUENU Yawoa Beatrice Djifa",
    "nom": "ADJOGUENU",
    "prenom": "Yawoa Beatrice Djifa",
    "manager_name": "YOMEKPE Komlan Agbenyigan",
    "date_mep": "19/08/2024",
    "contrat": "CDD",
    "statut_contrat": "CDD",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_bea",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_bea@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-1743",
    "matricule_rh": "1743",
    "nom_complet": "AMOUZOU Yawa Emmanuela",
    "nom": "AMOUZOU",
    "prenom": "Yawa Emmanuela",
    "manager_name": "SABI Prospere",
    "date_mep": "19/08/2024",
    "contrat": "CDI",
    "statut_contrat": "CDI N1",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_manuela",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_manuela@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-1744",
    "matricule_rh": "1744",
    "nom_complet": "ANAGO Komi Horacio",
    "nom": "ANAGO",
    "prenom": "Komi Horacio",
    "manager_name": "SABI Prospere",
    "date_mep": "19/08/2024",
    "contrat": "CDD",
    "statut_contrat": "CDD",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_ana",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_ana@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-1748",
    "matricule_rh": "1748",
    "nom_complet": "HOUNOU Têko José Daryl",
    "nom": "HOUNOU",
    "prenom": "Têko José Daryl",
    "manager_name": "SABI Prospere",
    "date_mep": "19/08/2024",
    "contrat": "CDD",
    "statut_contrat": "CDD",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_daryl",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_daryl@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-1751",
    "matricule_rh": "1751",
    "nom_complet": "NYAHENO Amivi Déladem",
    "nom": "NYAHENO",
    "prenom": "Amivi Déladem",
    "manager_name": "YOMEKPE Komlan Agbenyigan",
    "date_mep": "19/08/2024",
    "contrat": "CDD",
    "statut_contrat": "CDD",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_deladem",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_deladem@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-1752",
    "matricule_rh": "1752",
    "nom_complet": "NYAVOR Koukou There",
    "nom": "NYAVOR",
    "prenom": "Koukou There",
    "manager_name": "SABI Prospere",
    "date_mep": "19/08/2024",
    "contrat": "CDD",
    "statut_contrat": "CDD",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_there",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_there@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-1753",
    "matricule_rh": "1753",
    "nom_complet": "OUADJA Niko Diane",
    "nom": "OUADJA",
    "prenom": "Niko Diane",
    "manager_name": "HOUENASSOU Sidemeho Akofa",
    "date_mep": "19/08/2024",
    "contrat": "CDI",
    "statut_contrat": "CDI N1",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_diana",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_diana@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-1754",
    "matricule_rh": "1754",
    "nom_complet": "TOGBETSE Yawa Venunye",
    "nom": "TOGBETSE",
    "prenom": "Yawa Venunye",
    "manager_name": "HOUENASSOU Sidemeho Akofa",
    "date_mep": "19/08/2024",
    "contrat": "CDI",
    "statut_contrat": "CDI N1",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_venunye",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_venunye@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-1767",
    "matricule_rh": "1767",
    "nom_complet": "COCO Abla Bertille-Sandrine",
    "nom": "COCO",
    "prenom": "Abla Bertille-Sandrine",
    "manager_name": "HOUENASSOU Sidemeho Akofa",
    "date_mep": "09/09/2024",
    "contrat": "CDD",
    "statut_contrat": "CDD",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_bertille",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_bertille@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-1768",
    "matricule_rh": "1768",
    "nom_complet": "DOLAYI Denke Renaud Kodjo",
    "nom": "DOLAYI",
    "prenom": "Denke Renaud Kodjo",
    "manager_name": "KPONOOR ZAMAH Goudjo Yao Emile",
    "date_mep": "09/09/2024",
    "contrat": "CDD",
    "statut_contrat": "CDD",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_denke",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_denke@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-1772",
    "matricule_rh": "1772",
    "nom_complet": "ANANIVI Jean-Christian Martinien",
    "nom": "ANANIVI",
    "prenom": "Jean-Christian Martinien",
    "manager_name": "SABI Prospere",
    "date_mep": "09/09/2024",
    "contrat": "CDD",
    "statut_contrat": "CDD",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_martinien",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_martinien@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-1779",
    "matricule_rh": "1779",
    "nom_complet": "AHADJI Akouavi Essenam",
    "nom": "AHADJI",
    "prenom": "Akouavi Essenam",
    "manager_name": "SABI Prospere",
    "date_mep": "23/09/2024",
    "contrat": "CDD",
    "statut_contrat": "CDD",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_esenam",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_esenam@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-1780",
    "matricule_rh": "1780",
    "nom_complet": "AMEYAPOH Emmanuel Kodjo",
    "nom": "AMEYAPOH",
    "prenom": "Emmanuel Kodjo",
    "manager_name": "KPONOOR ZAMAH Goudjo Yao Emile",
    "date_mep": "23/09/2024",
    "contrat": "CDD",
    "statut_contrat": "CDD",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_manu",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_manu@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-1786",
    "matricule_rh": "1786",
    "nom_complet": "RAMANOU Kalaide Joseph Gnimdou",
    "nom": "RAMANOU",
    "prenom": "Kalaide Joseph Gnimdou",
    "manager_name": "KPONOOR ZAMAH Goudjo Yao Emile",
    "date_mep": "23/09/2024",
    "contrat": "CDD",
    "statut_contrat": "CDD",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_jo",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_jo@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-1814",
    "matricule_rh": "1814",
    "nom_complet": "TOUGAN Djiedjom Gilles",
    "nom": "TOUGAN",
    "prenom": "Djiedjom Gilles",
    "manager_name": "KPONOOR ZAMAH Goudjo Yao Emile",
    "date_mep": "23/09/2024",
    "contrat": "CDD",
    "statut_contrat": "CDD",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_gill",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_gill@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-1854",
    "matricule_rh": "1854",
    "nom_complet": "AFANGNAKOSSOU Kossi Carlos Clarck",
    "nom": "AFANGNAKOSSOU",
    "prenom": "Kossi Carlos Clarck",
    "manager_name": "YOMEKPE Komlan Agbenyigan",
    "date_mep": "07/10/2024",
    "contrat": "CDD",
    "statut_contrat": "CDD",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_clarck",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_clarck@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-1859",
    "matricule_rh": "1859",
    "nom_complet": "BOTOBAWI Patawanam",
    "nom": "BOTOBAWI",
    "prenom": "Patawanam",
    "manager_name": "YOMEKPE Komlan Agbenyigan",
    "date_mep": "07/10/2024",
    "contrat": "CDD",
    "statut_contrat": "CDD",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_patawanam",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_patawanam@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-1860",
    "matricule_rh": "1860",
    "nom_complet": "KOMLANVI Marie-Jessica Akouvi",
    "nom": "KOMLANVI",
    "prenom": "Marie-Jessica Akouvi",
    "manager_name": "YOMEKPE Komlan Agbenyigan",
    "date_mep": "07/10/2024",
    "contrat": "CDD",
    "statut_contrat": "CDD",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_jess",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_jess@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-1862",
    "matricule_rh": "1862",
    "nom_complet": "SOGBALI Elom Fernando Romuald",
    "nom": "SOGBALI",
    "prenom": "Elom Fernando Romuald",
    "manager_name": "KPONOOR ZAMAH Goudjo Yao Emile",
    "date_mep": "07/10/2024",
    "contrat": "CDD",
    "statut_contrat": "CDD",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_romuald",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_romuald@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-1863",
    "matricule_rh": "1863",
    "nom_complet": "YAKE Calice Bidema",
    "nom": "YAKE",
    "prenom": "Calice Bidema",
    "manager_name": "SABI Prospere",
    "date_mep": "07/10/2024",
    "contrat": "CDD",
    "statut_contrat": "CDD",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_calice",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_calice@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-1847",
    "matricule_rh": "1847",
    "nom_complet": "KOFFI Banabia Marguerite Gloria Dédé",
    "nom": "KOFFI",
    "prenom": "Banabia Marguerite Gloria Dédé",
    "manager_name": "HOUENASSOU Sidemeho Akofa",
    "date_mep": "20/05/2025",
    "contrat": "CDD",
    "statut_contrat": "CDD",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_marguerite",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_marguerite@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-1892",
    "matricule_rh": "1892",
    "nom_complet": "OLOUDE Tony-Mike",
    "nom": "OLOUDE",
    "prenom": "Tony-Mike",
    "manager_name": "SABI Prospere",
    "date_mep": "20/05/2025",
    "contrat": "CDD",
    "statut_contrat": "CDD",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_mike",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_mike@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-1905",
    "matricule_rh": "1905",
    "nom_complet": "MIHAMI Koffi Philippe",
    "nom": "MIHAMI",
    "prenom": "Koffi Philippe",
    "manager_name": "SABI Prospere",
    "date_mep": "20/05/2025",
    "contrat": "CDD",
    "statut_contrat": "CDD",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_philippe",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_philippe@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-2158",
    "matricule_rh": "2158",
    "nom_complet": "LAWSON Anoko Maude Victoire",
    "nom": "LAWSON",
    "prenom": "Anoko Maude Victoire",
    "manager_name": "YOMEKPE Komlan Agbenyigan",
    "date_mep": "20/05/2025",
    "contrat": "STG",
    "statut_contrat": "ANP",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_maude",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_maude@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-2159",
    "matricule_rh": "2159",
    "nom_complet": "LAWSON-DRACKEY Koko Ornella Marie-José",
    "nom": "LAWSON-DRACKEY",
    "prenom": "Koko Ornella Marie-José",
    "manager_name": "HOUENASSOU Sidemeho Akofa",
    "date_mep": "20/05/2025",
    "contrat": "STG",
    "statut_contrat": "ANP",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_drackey",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_drackey@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-2160",
    "matricule_rh": "2160",
    "nom_complet": "AYIKA Ekoue Godwin",
    "nom": "AYIKA",
    "prenom": "Ekoue Godwin",
    "manager_name": "HOUENASSOU Sidemeho Akofa",
    "date_mep": "20/05/2025",
    "contrat": "STG",
    "statut_contrat": "ANP",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_god",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_god@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-2161",
    "matricule_rh": "2161",
    "nom_complet": "SELODE Akossiwa Pascaline",
    "nom": "SELODE",
    "prenom": "Akossiwa Pascaline",
    "manager_name": "HOUENASSOU Sidemeho Akofa",
    "date_mep": "20/05/2025",
    "contrat": "STG",
    "statut_contrat": "ANP",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_pascaline",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_pascaline@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-2167",
    "matricule_rh": "2167",
    "nom_complet": "AGBAHOU Mario Kossi",
    "nom": "AGBAHOU",
    "prenom": "Mario Kossi",
    "manager_name": "BAHUN-WILSON Adjei Amos Annointed A.",
    "date_mep": "20/05/2025",
    "contrat": "STG",
    "statut_contrat": "ANP",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_marko",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_marko@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-2168",
    "matricule_rh": "2168",
    "nom_complet": "LAWSON Sibi Lolita",
    "nom": "LAWSON",
    "prenom": "Sibi Lolita",
    "manager_name": "SABI Prospere",
    "date_mep": "20/05/2025",
    "contrat": "STG",
    "statut_contrat": "ANP",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_sibita",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_sibita@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-799",
    "matricule_rh": "799",
    "nom_complet": "HOUEDJAGBAGBA Komlan Mawuko Clément",
    "nom": "HOUEDJAGBAGBA",
    "prenom": "Komlan Mawuko Clément",
    "manager_name": "SABI Prospere",
    "date_mep": "09/06/2025",
    "contrat": "CDI",
    "statut_contrat": "CDI N2",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_gbagba",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_gbagba@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-2173",
    "matricule_rh": "2173",
    "nom_complet": "AGBESSITONOU Regis Cedric",
    "nom": "AGBESSITONOU",
    "prenom": "Regis Cedric",
    "manager_name": "BAHUN-WILSON Adjei Amos Annointed A.",
    "date_mep": "09/06/2025",
    "contrat": "STG",
    "statut_contrat": "ANP",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_regis",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_regis@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-2177",
    "matricule_rh": "2177",
    "nom_complet": "GANKUI Marie-josé",
    "nom": "GANKUI",
    "prenom": "Marie-josé",
    "manager_name": "SABI Prospere",
    "date_mep": "09/06/2025",
    "contrat": "STG",
    "statut_contrat": "ANP",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_marijo",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_marijo@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-2178",
    "matricule_rh": "2178",
    "nom_complet": "KIDIKOUNE Emma",
    "nom": "KIDIKOUNE",
    "prenom": "Emma",
    "manager_name": "SABI Prospere",
    "date_mep": "09/06/2025",
    "contrat": "STG",
    "statut_contrat": "ANP",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_emma",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_emma@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-2179",
    "matricule_rh": "2179",
    "nom_complet": "KOURA Rihanatou",
    "nom": "KOURA",
    "prenom": "Rihanatou",
    "manager_name": "YOMEKPE Komlan Agbenyigan",
    "date_mep": "09/06/2025",
    "contrat": "STG",
    "statut_contrat": "ANP",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_rihana",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_rihana@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-2181",
    "matricule_rh": "2181",
    "nom_complet": "AMEGBOH-CLOUSSE Gerard Ferrer Mawuko",
    "nom": "AMEGBOH-CLOUSSE",
    "prenom": "Gerard Ferrer Mawuko",
    "manager_name": "KPONOOR ZAMAH Goudjo Yao Emile",
    "date_mep": "09/06/2025",
    "contrat": "STG",
    "statut_contrat": "ANP",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_ferrer",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_ferrer@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-2183",
    "matricule_rh": "2183",
    "nom_complet": "DZOKPE Afi Eyram Madeleine",
    "nom": "DZOKPE",
    "prenom": "Afi Eyram Madeleine",
    "manager_name": "KPONOOR ZAMAH Goudjo Yao Emile",
    "date_mep": "09/06/2025",
    "contrat": "STG",
    "statut_contrat": "ANP",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_madou",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_madou@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-2184",
    "matricule_rh": "2184",
    "nom_complet": "P'KLA Abdoul quddousse steven gnimdou",
    "nom": "P'KLA",
    "prenom": "Abdoul quddousse steven gnimdou",
    "manager_name": "BAHUN-WILSON Adjei Amos Annointed A.",
    "date_mep": "09/06/2025",
    "contrat": "STG",
    "statut_contrat": "ANP",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_douss",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_douss@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-467",
    "matricule_rh": "467",
    "nom_complet": "EKOUE Olivia Elise",
    "nom": "EKOUE",
    "prenom": "Olivia Elise",
    "manager_name": "BAHUN-WILSON Adjei Amos Annointed A.",
    "date_mep": "01/09/2025",
    "contrat": "CDD",
    "statut_contrat": "CDD",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_olivia",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_olivia@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-2342",
    "matricule_rh": "2342",
    "nom_complet": "AKAKPO Koffi Arsène",
    "nom": "AKAKPO",
    "prenom": "Koffi Arsène",
    "manager_name": "KPONOOR ZAMAH Goudjo Yao Emile",
    "date_mep": "01/09/2025",
    "contrat": "STG",
    "statut_contrat": "ANP",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_arsene",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_arsene@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-2343",
    "matricule_rh": "2343",
    "nom_complet": "AMELESSESSI Afi Marie-Hervé",
    "nom": "AMELESSESSI",
    "prenom": "Afi Marie-Hervé",
    "manager_name": "BAHUN-WILSON Adjei Amos Annointed A.",
    "date_mep": "01/09/2025",
    "contrat": "STG",
    "statut_contrat": "ANP",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_amarie",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_amarie@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-2345",
    "matricule_rh": "2345",
    "nom_complet": "AYENA Abla",
    "nom": "AYENA",
    "prenom": "Abla",
    "manager_name": "BAHUN-WILSON Adjei Amos Annointed A.",
    "date_mep": "01/09/2025",
    "contrat": "STG",
    "statut_contrat": "ANP",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_ayena",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_ayena@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-2346",
    "matricule_rh": "2346",
    "nom_complet": "AMESSE Dénise",
    "nom": "AMESSE",
    "prenom": "Dénise",
    "manager_name": "BAHUN-WILSON Adjei Amos Annointed A.",
    "date_mep": "01/09/2025",
    "contrat": "STG",
    "statut_contrat": "ANP",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_denise",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_denise@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-2347",
    "matricule_rh": "2347",
    "nom_complet": "AZANLEDJI Kokou Boniface",
    "nom": "AZANLEDJI",
    "prenom": "Kokou Boniface",
    "manager_name": "SABI Prospere",
    "date_mep": "01/09/2025",
    "contrat": "STG",
    "statut_contrat": "ANP",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_boniface",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_boniface@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-2350",
    "matricule_rh": "2350",
    "nom_complet": "HILIM Carine",
    "nom": "HILIM",
    "prenom": "Carine",
    "manager_name": "HOUENASSOU Sidemeho Akofa",
    "date_mep": "01/09/2025",
    "contrat": "STG",
    "statut_contrat": "ANP",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_carine",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_carine@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-2352",
    "matricule_rh": "2352",
    "nom_complet": "LAWSON HOINKA-MABOU Laté Franck-Olivier Benjamin",
    "nom": "LAWSON",
    "prenom": "HOINKA-MABOU Laté Franck-Olivier Benjamin",
    "manager_name": "HOUENASSOU Sidemeho Akofa",
    "date_mep": "01/09/2025",
    "contrat": "STG",
    "statut_contrat": "ANP",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_benjamin",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_benjamin@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-2355",
    "matricule_rh": "2355",
    "nom_complet": "TCHINLIEK Yendoula",
    "nom": "TCHINLIEK",
    "prenom": "Yendoula",
    "manager_name": "KPONOOR ZAMAH Goudjo Yao Emile",
    "date_mep": "01/09/2025",
    "contrat": "STG",
    "statut_contrat": "ANP",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_yendoula",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_yendoula@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-1658",
    "matricule_rh": "1658",
    "nom_complet": "DOSSAH Ayewanu Abel",
    "nom": "DOSSAH",
    "prenom": "Ayewanu Abel",
    "manager_name": "BAHUN-WILSON Adjei Amos Annointed A.",
    "date_mep": "15/10/2025",
    "contrat": "CDD",
    "statut_contrat": "CDD",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_ayewanu",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_ayewanu@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-2459",
    "matricule_rh": "2459",
    "nom_complet": "Abalo Eunice Abigayle Donssi",
    "nom": "Abalo",
    "prenom": "Eunice Abigayle Donssi",
    "manager_name": "YOMEKPE Komlan Agbenyigan",
    "date_mep": "06/10/2025",
    "contrat": "STG",
    "statut_contrat": "ANP",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_abigayle",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_abigayle@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-2462",
    "matricule_rh": "2462",
    "nom_complet": "DAKU Abla Nelly",
    "nom": "DAKU",
    "prenom": "Abla Nelly",
    "manager_name": "HOUENASSOU Sidemeho Akofa",
    "date_mep": "06/10/2025",
    "contrat": "STG",
    "statut_contrat": "ANP",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_nelly",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_nelly@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-2463",
    "matricule_rh": "2463",
    "nom_complet": "DJANKALE Abattan Kéboukou",
    "nom": "DJANKALE",
    "prenom": "Abattan Kéboukou",
    "manager_name": "BAHUN-WILSON Adjei Amos Annointed A.",
    "date_mep": "06/10/2025",
    "contrat": "STG",
    "statut_contrat": "ANP",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_keboukou",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_keboukou@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-2464",
    "matricule_rh": "2464",
    "nom_complet": "EKLO Amoussula Yao",
    "nom": "EKLO",
    "prenom": "Amoussula Yao",
    "manager_name": "HOUENASSOU Sidemeho Akofa",
    "date_mep": "06/10/2025",
    "contrat": "STG",
    "statut_contrat": "ANP",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_eklo",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_eklo@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-2465",
    "matricule_rh": "2465",
    "nom_complet": "ISSIFOU Simia Limata",
    "nom": "ISSIFOU",
    "prenom": "Simia Limata",
    "manager_name": "HOUENASSOU Sidemeho Akofa",
    "date_mep": "06/10/2025",
    "contrat": "STG",
    "statut_contrat": "ANP",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_limata",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_limata@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-2468",
    "matricule_rh": "2468",
    "nom_complet": "SABY-KEKELE Rachida",
    "nom": "SABY-KEKELE",
    "prenom": "Rachida",
    "manager_name": "HOUENASSOU Sidemeho Akofa",
    "date_mep": "06/10/2025",
    "contrat": "STG",
    "statut_contrat": "ANP",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_rachida",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_rachida@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-2516",
    "matricule_rh": "2516",
    "nom_complet": "KUEVI Ekue Pascal Eli",
    "nom": "KUEVI",
    "prenom": "Ekue Pascal Eli",
    "manager_name": "BAHUN-WILSON Adjei Amos Annointed A.",
    "date_mep": "15/10/2025",
    "contrat": "STG",
    "statut_contrat": "ANP",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_kuevi",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_kuevi@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-2582",
    "matricule_rh": "2582",
    "nom_complet": "AFANOU Akouvi Manavi Simone",
    "nom": "AFANOU",
    "prenom": "Akouvi Manavi Simone",
    "manager_name": "KPONOOR ZAMAH Goudjo Yao Emile",
    "date_mep": "12/11/2025",
    "contrat": "STG",
    "statut_contrat": "ANP",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_simone",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_simone@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-2583",
    "matricule_rh": "2583",
    "nom_complet": "Akakpo Adjo Rose",
    "nom": "Akakpo",
    "prenom": "Adjo Rose",
    "manager_name": "BAHUN-WILSON Adjei Amos Annointed A.",
    "date_mep": "12/11/2025",
    "contrat": "STG",
    "statut_contrat": "ANP",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_rose",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_rose@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-2585",
    "matricule_rh": "2585",
    "nom_complet": "AMOUZOU Koudjo Honoré",
    "nom": "AMOUZOU",
    "prenom": "Koudjo Honoré",
    "manager_name": "KPONOOR ZAMAH Goudjo Yao Emile",
    "date_mep": "12/11/2025",
    "contrat": "STG",
    "statut_contrat": "ANP",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_honore",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_honore@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-2171",
    "matricule_rh": "2171",
    "nom_complet": "BADASSOU Afi Ira",
    "nom": "BADASSOU",
    "prenom": "Afi Ira",
    "manager_name": "BAHUN-WILSON Adjei Amos Annointed A.",
    "date_mep": "20/05/2025",
    "contrat": "STG",
    "statut_contrat": "ANP",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_ira",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_ira@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-2349",
    "matricule_rh": "2349",
    "nom_complet": "GADU Komi Pascal",
    "nom": "GADU",
    "prenom": "Komi Pascal",
    "manager_name": "BAHUN-WILSON Adjei Amos Annointed A.",
    "date_mep": "01/09/2025",
    "contrat": "STG",
    "statut_contrat": "ANP",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_pascal",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_pascal@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-2351",
    "matricule_rh": "2351",
    "nom_complet": "KOUNTA Abravi Aïcha",
    "nom": "KOUNTA",
    "prenom": "Abravi Aïcha",
    "manager_name": "KPONOOR ZAMAH Goudjo Yao Emile",
    "date_mep": "01/09/2025",
    "contrat": "STG",
    "statut_contrat": "ANP",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_kounta",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_kounta@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-2354",
    "matricule_rh": "2354",
    "nom_complet": "N'BIBA Napo",
    "nom": "N'BIBA",
    "prenom": "Napo",
    "manager_name": "HOUENASSOU Sidemeho Akofa",
    "date_mep": "01/09/2025",
    "contrat": "STG",
    "statut_contrat": "ANP",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_nabi",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_nabi@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  },
  {
    "id": "agent-2461",
    "matricule_rh": "2461",
    "nom_complet": "AMANA Hèzouwè",
    "nom": "AMANA",
    "prenom": "Hèzouwè",
    "manager_name": "BAHUN-WILSON Adjei Amos Annointed A.",
    "date_mep": "06/10/2025",
    "contrat": "STG",
    "statut_contrat": "ANP",
    "anciennete": "+ 3 mois",
    "log_activite": "lom_ama",
    "premier_login": true,
    "statut": "actif",
    "email": "lom_ama@amazon-support.com",
    "role": "agent",
    "xp": 250,
    "niveau": 1,
    "badges": []
  }
];

export const INITIAL_WEEKLY_PERFORMANCES: WeeklyPerformance[] = [
  // S31 - TATOUNOU Shalom
  {
    id: 'perf-1163-s31-phone',
    agent_id: 'agent-1163',
    agent_name: 'TATOUNOU Shalom',
    log_activite: 'lom_tatounou',
    manager_name: 'SABI Prospere',
    canal: 'Phone',
    semaine: 31,
    annee: 2026,
    yes: 185,
    no: 35,
    rap: 0.839,
    ccx: 0.906,
    tr: 0.141,
    dmt: 562,
    vol: 360,
    h_planifiees: 40,
    h_absence: 0,
    statut: 'En progression',
    feedback: 'Bonne gestion du volume Phone. L’écoute active et la réduction de la durée de traitement permettent de maintenir le DMT dans l’objectif.',
    axes_amelioration: 'Maintenir le focus sur la résolution au premier contact (RAP) pour dépasser 85%.',
    commentaires: 'Progression continue sur la fluidité des appels.',
    coaching: 'Concentrer les efforts sur la qualification directe du besoin client.',
    plan_action: 'Revoir le script de clarification initiale pendant 5 min chaque début de shift.',
  },
  {
    id: 'perf-1163-s31-email',
    agent_id: 'agent-1163',
    agent_name: 'TATOUNOU Shalom',
    log_activite: 'lom_tatounou',
    manager_name: 'SABI Prospere',
    canal: 'Email',
    semaine: 31,
    annee: 2026,
    yes: 140,
    no: 25,
    rap: 0.841,
    ccx: 0.937,
    tr: 0.188,
    dmt: 641,
    vol: 190,
    h_planifiees: 20,
    h_absence: 0,
    statut: 'Objectif atteint',
    feedback: 'Excellente rédaction des réponses email, CCX très satisfaisant.',
  },
  {
    id: 'perf-1163-s31-mu',
    agent_id: 'agent-1163',
    agent_name: 'TATOUNOU Shalom',
    log_activite: 'lom_tatounou',
    manager_name: 'SABI Prospere',
    canal: 'MU',
    semaine: 31,
    annee: 2026,
    yes: 120,
    no: 22,
    rap: 0.829,
    ccx: 0.933,
    tr: 0.191,
    dmt: 716,
    vol: 140,
    h_planifiees: 15,
    h_absence: 0,
    statut: 'À renforcer',
  },

  // S30 - TATOUNOU Shalom
  {
    id: 'perf-1163-s30-phone',
    agent_id: 'agent-1163',
    agent_name: 'TATOUNOU Shalom',
    log_activite: 'lom_tatounou',
    manager_name: 'SABI Prospere',
    canal: 'Phone',
    semaine: 30,
    annee: 2026,
    yes: 160,
    no: 40,
    rap: 0.679,
    ccx: 0.875,
    tr: 0.254,
    dmt: 0,
    vol: 220,
    h_planifiees: 35,
    h_absence: 2,
    statut: 'À renforcer',
    feedback: 'Taux de transfert anormalement élevé cette semaine. Réviser la grille d’escalade.',
  },
  {
    id: 'perf-1163-s30-email',
    agent_id: 'agent-1163',
    agent_name: 'TATOUNOU Shalom',
    log_activite: 'lom_tatounou',
    manager_name: 'SABI Prospere',
    canal: 'Email',
    semaine: 30,
    annee: 2026,
    yes: 150,
    no: 26,
    rap: 0.850,
    ccx: 0.958,
    tr: 0.205,
    dmt: 642,
    vol: 180,
  },
  {
    id: 'perf-1163-s30-mu',
    agent_id: 'agent-1163',
    agent_name: 'TATOUNOU Shalom',
    log_activite: 'lom_tatounou',
    manager_name: 'SABI Prospere',
    canal: 'MU',
    semaine: 30,
    annee: 2026,
    yes: 130,
    no: 22,
    rap: 0.854,
    ccx: 0.925,
    tr: 0.265,
    dmt: 0,
    vol: 150,
  },

  // S29 - TATOUNOU Shalom
  {
    id: 'perf-1163-s29-phone',
    agent_id: 'agent-1163',
    agent_name: 'TATOUNOU Shalom',
    log_activite: 'lom_tatounou',
    manager_name: 'SABI Prospere',
    canal: 'Phone',
    semaine: 29,
    annee: 2026,
    rap: 0.831,
    tr: 0.150,
    ccx: 0.920,
    dmt: 668,
    vol: 310,
  },
  {
    id: 'perf-1163-s29-email',
    agent_id: 'agent-1163',
    agent_name: 'TATOUNOU Shalom',
    log_activite: 'lom_tatounou',
    manager_name: 'SABI Prospere',
    canal: 'Email',
    semaine: 29,
    annee: 2026,
    rap: 0.829,
    tr: 0.187,
    ccx: 0.934,
    dmt: 651,
    vol: 175,
  },
  {
    id: 'perf-1163-s29-mu',
    agent_id: 'agent-1163',
    agent_name: 'TATOUNOU Shalom',
    log_activite: 'lom_tatounou',
    manager_name: 'SABI Prospere',
    canal: 'MU',
    semaine: 29,
    annee: 2026,
    rap: 0.850,
    tr: 0.226,
    ccx: 0.934,
    dmt: 705,
    vol: 160,
  },

  // S28 - TATOUNOU Shalom
  {
    id: 'perf-1163-s28-phone',
    agent_id: 'agent-1163',
    agent_name: 'TATOUNOU Shalom',
    log_activite: 'lom_tatounou',
    manager_name: 'SABI Prospere',
    canal: 'Phone',
    semaine: 28,
    annee: 2026,
    rap: 0.820,
    tr: 0.129,
    ccx: 0.906,
    dmt: 551,
    vol: 290,
  },
  {
    id: 'perf-1163-s28-email',
    agent_id: 'agent-1163',
    agent_name: 'TATOUNOU Shalom',
    log_activite: 'lom_tatounou',
    manager_name: 'SABI Prospere',
    canal: 'Email',
    semaine: 28,
    annee: 2026,
    rap: 0.863,
    tr: 0.188,
    ccx: 0.948,
    dmt: 680,
    vol: 180,
  },

  // S27 - TATOUNOU Shalom
  {
    id: 'perf-1163-s27-phone',
    agent_id: 'agent-1163',
    agent_name: 'TATOUNOU Shalom',
    log_activite: 'lom_tatounou',
    manager_name: 'SABI Prospere',
    canal: 'Phone',
    semaine: 27,
    annee: 2026,
    rap: 0.828,
    tr: 0.163,
    ccx: 0.906,
    dmt: 621,
    vol: 280,
  },

  // S31 - AZANLEDJI Kokou Boniface
  {
    id: 'perf-2347-s31-phone',
    agent_id: 'agent-2347',
    agent_name: 'AZANLEDJI Kokou Boniface',
    log_activite: 'lom_boniface',
    manager_name: 'SABI Prospere',
    canal: 'Phone',
    semaine: 31,
    annee: 2026,
    rap: 0.810,
    tr: 0.142,
    ccx: 0.902,
    dmt: 570,
    vol: 360,
  },
  {
    id: 'perf-2347-s31-email',
    agent_id: 'agent-2347',
    agent_name: 'AZANLEDJI Kokou Boniface',
    log_activite: 'lom_boniface',
    manager_name: 'SABI Prospere',
    canal: 'Email',
    semaine: 31,
    annee: 2026,
    rap: 0.842,
    tr: 0.183,
    ccx: 0.938,
    dmt: 729,
    vol: 54,
  },
  {
    id: 'perf-2347-s31-mu',
    agent_id: 'agent-2347',
    agent_name: 'AZANLEDJI Kokou Boniface',
    log_activite: 'lom_boniface',
    manager_name: 'SABI Prospere',
    canal: 'MU',
    semaine: 31,
    annee: 2026,
    rap: 0.823,
    tr: 0.193,
    ccx: 0.960,
    dmt: 729,
    vol: 67,
  },

  // S31 - GANKUI Marie-josé
  {
    id: 'perf-2177-s31-phone',
    agent_id: 'agent-2177',
    agent_name: 'GANKUI Marie-josé',
    log_activite: 'lom_marijo',
    manager_name: 'SABI Prospere',
    canal: 'Phone',
    semaine: 31,
    annee: 2026,
    rap: 0.826,
    tr: 0.145,
    ccx: 0.901,
    dmt: 650,
    vol: 221,
  },
  {
    id: 'perf-2177-s31-email',
    agent_id: 'agent-2177',
    agent_name: 'GANKUI Marie-josé',
    log_activite: 'lom_marijo',
    manager_name: 'SABI Prospere',
    canal: 'Email',
    semaine: 31,
    annee: 2026,
    rap: 0.845,
    tr: 0.182,
    ccx: 0.954,
    dmt: 665,
    vol: 79,
  },
  {
    id: 'perf-2177-s31-mu',
    agent_id: 'agent-2177',
    agent_name: 'GANKUI Marie-josé',
    log_activite: 'lom_marijo',
    manager_name: 'SABI Prospere',
    canal: 'MU',
    semaine: 31,
    annee: 2026,
    rap: 0.822,
    tr: 0.220,
    ccx: 0.941,
    dmt: 716,
    vol: 71,
  },

  // S31 - KIDIKOUNE Emma
  {
    id: 'perf-2178-s31-phone',
    agent_id: 'agent-2178',
    agent_name: 'KIDIKOUNE Emma',
    log_activite: 'lom_emma',
    manager_name: 'SABI Prospere',
    canal: 'Phone',
    semaine: 31,
    annee: 2026,
    rap: 0.826,
    tr: 0.174,
    ccx: 0.934,
    dmt: 564,
    vol: 309,
  },
  {
    id: 'perf-2178-s31-email',
    agent_id: 'agent-2178',
    agent_name: 'KIDIKOUNE Emma',
    log_activite: 'lom_emma',
    manager_name: 'SABI Prospere',
    canal: 'Email',
    semaine: 31,
    annee: 2026,
    rap: 0.874,
    tr: 0.223,
    ccx: 0.937,
    dmt: 682,
    vol: 79,
  },
  {
    id: 'perf-2178-s31-mu',
    agent_id: 'agent-2178',
    agent_name: 'KIDIKOUNE Emma',
    log_activite: 'lom_emma',
    manager_name: 'SABI Prospere',
    canal: 'MU',
    semaine: 31,
    annee: 2026,
    rap: 0.871,
    tr: 0.192,
    ccx: 0.946,
    dmt: 690,
    vol: 119,
  },

  // S31 - HOUEDJAGBAGBA Komlan Mawuko Clément
  {
    id: 'perf-799-s31-phone',
    agent_id: 'agent-799',
    agent_name: 'HOUEDJAGBAGBA Komlan Mawuko Clément',
    log_activite: 'lom_gbagba',
    manager_name: 'SABI Prospere',
    canal: 'Phone',
    semaine: 31,
    annee: 2026,
    rap: 0.855,
    tr: 0.120,
    ccx: 0.929,
    dmt: 607,
    vol: 300,
  },
  {
    id: 'perf-799-s31-email',
    agent_id: 'agent-799',
    agent_name: 'HOUEDJAGBAGBA Komlan Mawuko Clément',
    log_activite: 'lom_gbagba',
    manager_name: 'SABI Prospere',
    canal: 'Email',
    semaine: 31,
    annee: 2026,
    rap: 0.820,
    tr: 0.216,
    ccx: 0.946,
    dmt: 677,
    vol: 121,
  },
  {
    id: 'perf-799-s31-mu',
    agent_id: 'agent-799',
    agent_name: 'HOUEDJAGBAGBA Komlan Mawuko Clément',
    log_activite: 'lom_gbagba',
    manager_name: 'SABI Prospere',
    canal: 'MU',
    semaine: 31,
    annee: 2026,
    rap: 0.864,
    tr: 0.206,
    ccx: 0.944,
    dmt: 654,
    vol: 30,
  },

  // S31 - LAWSON Sibi Lolita
  {
    id: 'perf-2168-s31-phone',
    agent_id: 'agent-2168',
    agent_name: 'LAWSON Sibi Lolita',
    log_activite: 'lom_sibita',
    manager_name: 'SABI Prospere',
    canal: 'Phone',
    semaine: 31,
    annee: 2026,
    rap: 0.813,
    tr: 0.137,
    ccx: 0.920,
    dmt: 588,
    vol: 283,
  },

  // S31 - TATRA Aman Emefa
  {
    id: 'perf-551-s31-phone',
    agent_id: 'agent-551',
    agent_name: 'TATRA Aman Emefa',
    log_activite: 'lom_amane',
    manager_name: 'SABI Prospere',
    canal: 'Phone',
    semaine: 31,
    annee: 2026,
    rap: 0.835,
    tr: 0.143,
    ccx: 0.935,
    dmt: 638,
    vol: 317,
  },

  // S31 - NTSUYIBOE Joanita
  {
    id: 'perf-1132-s31-phone',
    agent_id: 'agent-1132',
    agent_name: 'NTSUYIBOE Joanita',
    log_activite: 'lom_joanita',
    manager_name: 'SABI Prospere',
    canal: 'Phone',
    semaine: 31,
    annee: 2026,
    rap: 0.859,
    tr: 0.125,
    ccx: 0.942,
    dmt: 545,
    vol: 380,
  },

  // S31 - OLOUDE Tony-Mike
  {
    id: 'perf-1892-s31-phone',
    agent_id: 'agent-1892',
    agent_name: 'OLOUDE Tony-Mike',
    log_activite: 'lom_mike',
    manager_name: 'SABI Prospere',
    canal: 'Phone',
    semaine: 31,
    annee: 2026,
    rap: 0.859,
    tr: 0.166,
    ccx: 0.907,
    dmt: 652,
    vol: 225,
  },

  // S31 - MIHAMI Koffi Philippe
  {
    id: 'perf-1905-s31-phone',
    agent_id: 'agent-1905',
    agent_name: 'MIHAMI Koffi Philippe',
    log_activite: 'lom_philippe',
    manager_name: 'SABI Prospere',
    canal: 'Phone',
    semaine: 31,
    annee: 2026,
    rap: 0.852,
    tr: 0.120,
    ccx: 0.913,
    dmt: 582,
    vol: 168,
  },

  // S31 - YAKE Calice Bidema
  {
    id: 'perf-1863-s31-phone',
    agent_id: 'agent-1863',
    agent_name: 'YAKE Calice Bidema',
    log_activite: 'lom_calice',
    manager_name: 'SABI Prospere',
    canal: 'Phone',
    semaine: 31,
    annee: 2026,
    rap: 0.822,
    tr: 0.138,
    ccx: 0.925,
    dmt: 556,
    vol: 344,
  },

  // S31 - DOSSEH Yawa Sandrine
  {
    id: 'perf-517-s31-phone',
    agent_id: 'agent-517',
    agent_name: 'DOSSEH Yawa Sandrine',
    log_activite: 'lom_yawad',
    manager_name: 'SABI Prospere',
    canal: 'Phone',
    semaine: 31,
    annee: 2026,
    rap: 0.819,
    tr: 0.167,
    ccx: 0.911,
    dmt: 664,
    vol: 144,
  },
];

export const INITIAL_MONTHLY_RESULTS: MonthlyResult[] = [
  {
    id: 'mres-1163-202607',
    agent_id: 'agent-1163',
    matricule_rh: '1163',
    agent_name: 'TATOUINOU Shalom',
    manager_name: 'SABI Prospere',
    anciennete: '+ 3 mois',
    mois_label: 'Juillet 2026',
    mois_key: '2026-07',
    annee: 2026,
    numero_mois: 7,
    vol_total: 1970,
    poids_phone: 62.5,
    poids_email: 22.3,
    poids_mu: 15.2,
    contrib_phone: 12500,
    contrib_email: 5200,
    contrib_mu: 4400,
    pv_sans_presence: 22100,
    presence: 93.14,
    pv_finale: 20669,
    statut: 'En progression',
    commentaire: 'Bon comportement global. Travailler la maîtrise du DMT sur le canal MU.',
  },
  {
    id: 'mres-1132-202607',
    agent_id: 'agent-1132',
    matricule_rh: '1132',
    agent_name: 'NTSUYIBOE Joanita',
    manager_name: 'SABI Prospere',
    anciennete: '+ 3 mois',
    mois_label: 'Juillet 2026',
    mois_key: '2026-07',
    annee: 2026,
    numero_mois: 7,
    vol_total: 1364,
    poids_phone: 75.0,
    poids_email: 15.0,
    poids_mu: 10.0,
    contrib_phone: 28500,
    contrib_email: 6200,
    contrib_mu: 4400,
    pv_sans_presence: 39100,
    presence: 91.75,
    pv_finale: 35910,
    statut: 'En progression',
  },
  {
    id: 'mres-551-202607',
    agent_id: 'agent-551',
    matricule_rh: '551',
    agent_name: 'TATRA Aman Emefa',
    manager_name: 'SABI Prospere',
    anciennete: '+ 3 mois',
    mois_label: 'Juillet 2026',
    mois_key: '2026-07',
    annee: 2026,
    numero_mois: 7,
    vol_total: 1206,
    poids_phone: 80.0,
    poids_email: 12.0,
    poids_mu: 8.0,
    contrib_phone: 26000,
    contrib_email: 5200,
    contrib_mu: 3000,
    pv_sans_presence: 34200,
    presence: 89.18,
    pv_finale: 30516,
    statut: 'En progression',
  },
  {
    id: 'mres-1752-202607',
    agent_id: 'agent-1752',
    matricule_rh: '1752',
    agent_name: 'NYAVOR Koukou There',
    manager_name: 'SABI Prospere',
    anciennete: '+ 3 mois',
    mois_label: 'Juillet 2026',
    mois_key: '2026-07',
    annee: 2026,
    numero_mois: 7,
    vol_total: 1850,
    poids_phone: 70.0,
    poids_email: 20.0,
    poids_mu: 10.0,
    contrib_phone: 24000,
    contrib_email: 5800,
    contrib_mu: 4000,
    pv_sans_presence: 33800,
    presence: 90.08,
    pv_finale: 30448,
    statut: 'En progression',
  },
  {
    id: 'mres-2178-202607',
    agent_id: 'agent-2178',
    matricule_rh: '2178',
    agent_name: 'KIDIKOUNE Emma',
    manager_name: 'SABI Prospere',
    anciennete: '+ 3 mois',
    mois_label: 'Juillet 2026',
    mois_key: '2026-07',
    annee: 2026,
    numero_mois: 7,
    vol_total: 1927,
    poids_phone: 61.0,
    poids_email: 15.5,
    poids_mu: 23.5,
    contrib_phone: 18500,
    contrib_email: 6100,
    contrib_mu: 5750,
    pv_sans_presence: 30350,
    presence: 96.48,
    pv_finale: 29274,
    statut: 'En progression',
  },
  {
    id: 'mres-1779-202607',
    agent_id: 'agent-1779',
    matricule_rh: '1779',
    agent_name: 'AHADJI Akouavi Essenam',
    manager_name: 'SABI Prospere',
    anciennete: '+ 3 mois',
    mois_label: 'Juillet 2026',
    mois_key: '2026-07',
    annee: 2026,
    numero_mois: 7,
    vol_total: 1450,
    poids_phone: 68.0,
    poids_email: 20.0,
    poids_mu: 12.0,
    contrib_phone: 20000,
    contrib_email: 5500,
    contrib_mu: 4400,
    pv_sans_presence: 29900,
    presence: 96.17,
    pv_finale: 28754,
    statut: 'En progression',
  },
  {
    id: 'mres-2168-202607',
    agent_id: 'agent-2168',
    matricule_rh: '2168',
    agent_name: 'LAWSON Sibi Lolita',
    manager_name: 'SABI Prospere',
    anciennete: '+ 3 mois',
    mois_label: 'Juillet 2026',
    mois_key: '2026-07',
    annee: 2026,
    numero_mois: 7,
    vol_total: 2138,
    pv_sans_presence: 16000,
    presence: 94.22,
    pv_finale: 15071,
    statut: 'À renforcer',
  },
  {
    id: 'mres-2347-202607',
    agent_id: 'agent-2347',
    matricule_rh: '2347',
    agent_name: 'AZANLEDJI Kokou Boniface',
    manager_name: 'SABI Prospere',
    anciennete: '+ 3 mois',
    mois_label: 'Juillet 2026',
    mois_key: '2026-07',
    annee: 2026,
    numero_mois: 7,
    vol_total: 1922,
    pv_sans_presence: 26800,
    presence: 94.28,
    pv_finale: 25336,
    statut: 'En progression',
  },
  {
    id: 'mres-1036-202607',
    agent_id: 'agent-1036',
    matricule_rh: '1036',
    agent_name: 'PEKEMSI Edmond Eyana',
    manager_name: 'SABI Prospere',
    anciennete: '+ 3 mois',
    mois_label: 'Juillet 2026',
    mois_key: '2026-07',
    annee: 2026,
    numero_mois: 7,
    vol_total: 1495,
    pv_sans_presence: 29250,
    presence: 88.99,
    pv_finale: 26035,
    statut: 'En progression',
  },
  {
    id: 'mres-2177-202607',
    agent_id: 'agent-2177',
    matricule_rh: '2177',
    agent_name: 'GANKUI Marie-josé',
    manager_name: 'SABI Prospere',
    anciennete: '+ 3 mois',
    mois_label: 'Juillet 2026',
    mois_key: '2026-07',
    annee: 2026,
    numero_mois: 7,
    vol_total: 1520,
    pv_sans_presence: 27500,
    presence: 92.50,
    pv_finale: 25437,
    statut: 'En progression',
  },
  {
    id: 'mres-1032-202607',
    agent_id: 'agent-1032',
    matricule_rh: '1032',
    agent_name: 'GBOGBO Aba Yawa Abigaïl Gloria',
    manager_name: 'SABI Prospere',
    anciennete: '+ 3 mois',
    mois_label: 'Juillet 2026',
    mois_key: '2026-07',
    annee: 2026,
    numero_mois: 7,
    vol_total: 1897,
    pv_sans_presence: 16250,
    presence: 93.26,
    pv_finale: 15163,
    statut: 'À renforcer',
  },
];

export const INITIAL_RCAS: RCA[] = [
  {
    id: 'rca-1',
    agent_id: 'agent-1163',
    agent_name: 'TATOUNOU Shalom',
    semaine: 30,
    annee: 2026,
    kpi_concerne: 'TR',
    description: 'Taux de transfert anormalement élevé (25.4% vs cible 14.5%) en S30 sur le canal Phone.',
    analyse_cause: 'Escalade prématurée vers le N2 lors des demandes de remboursement complexes sur produits reconditionnés sans vérifier la FAQ V2.',
    statut: 'en_cours',
    priorite: 'haute',
    created_by_name: 'SABI Prospere',
  },
  {
    id: 'rca-2',
    agent_id: 'agent-2347',
    agent_name: 'AZANLEDJI Kokou Boniface',
    semaine: 31,
    annee: 2026,
    kpi_concerne: 'DMT',
    description: 'DMT Email & MU supérieur à 720s en S31.',
    analyse_cause: 'Recherche manuelle d’informations de livraison au lieu de consulter directement le portail logistique interne.',
    statut: 'ouvert',
    priorite: 'moyenne',
    created_by_name: 'SABI Prospere',
  },
];

export const INITIAL_ACTION_ITEMS: ActionItem[] = [
  {
    id: 'act-1',
    rca_id: 'rca-1',
    agent_id: 'agent-1163',
    agent_name: 'TATOUNOU Shalom',
    action: 'Session de formation de 30 min sur l’arbre de décision de remboursement.',
    responsable: 'Formateur / Manager',
    echeance: '2026-08-15',
    statut: 'en_cours',
    progres: 50,
  },
  {
    id: 'act-2',
    rca_id: 'rca-1',
    agent_id: 'agent-1163',
    agent_name: 'TATOUNOU Shalom',
    action: 'Double écoute de 5 appels avec transfert par le manager.',
    responsable: 'SABI Prospere',
    echeance: '2026-08-18',
    statut: 'a_faire',
    progres: 0,
  },
  {
    id: 'act-3',
    rca_id: 'rca-2',
    agent_id: 'agent-2347',
    agent_name: 'AZANLEDJI Kokou Boniface',
    action: 'Mettre à jour les raccourcis navigateur vers le portail suivi colis.',
    responsable: 'AZANLEDJI Kokou Boniface',
    echeance: '2026-08-12',
    statut: 'a_faire',
    progres: 0,
  },
];

export const INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    agent_id: 'agent-1163',
    type: 'info',
    titre: 'Nouveau feedback - S31',
    message: 'SABI Prospere a publié votre feedback pour la semaine 31. Consultez-le dans votre espace.',
    lu: false,
    semaine: 31,
    kpi: 'feedback',
    created_date: '2026-08-05T10:00:00Z',
  },
  {
    id: 'notif-2',
    agent_id: 'agent-1163',
    type: 'success',
    titre: 'Objectif atteint en S31 !',
    message: 'Félicitations, vous avez atteint l’objectif sur le canal Email en S31.',
    lu: false,
    semaine: 31,
    kpi: 'rap',
    created_date: '2026-08-06T14:30:00Z',
  },
];
